trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8'
  displayName: 'Iniciando Python 3.8'

- script: |
    python -m pip install --upgrade pip
    pip install --upgrade pip setuptools wheel
    pip install -r requirements.txt  # Instala as dependências do projeto
  displayName: 'Instalar Dependências'

- script: |
    python -m unittest discover  # Executa os testes
  displayName: 'Executar Testes'

- script: |
    python setup.py bdist_wheel  # Cria um pacote Wheel
  displayName: 'Construir Pacote'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/Package.zip'
    replaceExistingArchive: true

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)/Package.zip'
    artifact: 'PackageZip'
